# Generated by Django 4.2.16 on 2024-11-19 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='users', to='movies.genre'),
        ),
        migrations.AddField(
            model_name='user',
            name='userImage',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
