# Generated by Django 4.2.7 on 2023-11-21 12:23

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254)),
                ('nickname', models.CharField(max_length=254, unique=True)),
                ('address', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('남성', '남성'), ('여성', '여성')], max_length=3)),
                ('birthday', models.CharField(blank=True, max_length=8, null=True)),
                ('interest', models.CharField(choices=[('내집마련', '내집마련'), ('재태크', '재태크'), ('신혼여행', '신혼여행'), ('출산', '출산')], max_length=10)),
                ('married_period', models.IntegerField(blank=True, null=True)),
                ('saving_target_period', models.IntegerField(blank=True, null=True)),
                ('main_bank', models.CharField(choices=[('우리은행', '우리은행'), ('한국스탠다드차타드은행', '한국스탠다드차타드은행'), ('대구은행', '대구은행'), ('부산은행', '부산은행'), ('광주은행', '광주은행'), ('제주은행', '제주은행'), ('전북은행', '전북은행'), ('경남은행', '경남은행'), ('중소기업은행', '중소기업은행'), ('한국산업은행', '한국산업은행'), ('국민은행', '국민은행'), ('신한은행', '신한은행'), ('농협은행', '농협은행'), ('하나은행', '하나은행'), ('수협은행', '수협은행'), ('카카오뱅크', '주식회사 카카오뱅크'), ('주식회사 케이뱅크', '주식회사 케이뱅크'), ('토스뱅크 주식회사', '토스뱅크 주식회사'), ('기타', '기타')], max_length=15)),
                ('couple_nickname', models.CharField(blank=True, max_length=254, null=True)),
                ('couple_birthday', models.CharField(blank=True, max_length=8, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
